[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=61" ]

[project]
name = "openfisca-excel-reform"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "openfisca-core[web-api]>=43",
]

[dependency-groups]
dev = [
    "openfisca-country-template>=8.0.3",
    "pytest>=8,<9.0",
]
